# -*- coding: utf-8 -*-
"""Código R e LCDM - H.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HhQYvsVTgdo_Kuo3iz8-O4CeXaBFLlLp
"""

import matplotlib.pyplot as plt
import numpy as np
from numpy import loadtxt, savetxt
import pyccl as ccl
plt.rcParams['text.usetex'] = True
from gapp import gp

# primeira derivada

from gapp import dgp

# definindo constantes
c = 2.9*10**5 # velocidade da luz
h0 = 67.27 #km/s/Mpc

data_H = np.genfromtxt('/home/usuario/Documentos/Dados/CC_Hz_data (cópia).csv', delimiter=', ')

z = data_H[:,0]
H = data_H[:,1]
sig_H = data_H[:,2]


# nomeando
x_gapp = z
y_gapp = H
e = sig_H

# xmin, xmax and nstar are interpreted as two-dimensional vectors
xmin = 0
xmax = 1.0
nstar = 1000

# initial values of the hyperparameters of the squared-exponential covariance function
initheta = [2.0, 2.0]

# initialization of the Gaussian Process
g = gp.GaussianProcess(x_gapp, y_gapp, e, cXstar=(xmin, xmax, nstar))

# training of the hyperparameters and reconstruction of the function
(rec, theta) = g.gp(theta=initheta)

xi = rec[:, 0]

y_pred = rec[:, 1]
sigma  = rec[:, 2]

y_pred_95_less = y_pred - 1.9600*sigma
y_pred_95_plus = y_pred + 1.9600*sigma


# salvando os dados reconstruídos

F = xi, y_pred, sigma
#np.savetxt('H_recon_gapp.csv', np.transpose(F), delimiter=', ')



# MODELO LCDM


cosmo = ccl.Cosmology(
    Omega_c=0.2656, Omega_b=0.0494, h=0.6727, sigma8=0.8120, n_s=0.9649,
    matter_power_spectrum='linear')


zlcdm = np.linspace(0.001, 1.0, 1000)

a = 1. / (1. + zlcdm)

hlcdm = h0*ccl.background.h_over_h0(cosmo, a)



# comparando

dH = y_pred - hlcdm
sig_dH = sigma


# Plot the function, the prediction and the 95% confidence interval
plt.figure()
plt.ylim(-15,15)
plt.xlim(0,1.0)
plt.tick_params(labelsize=14, color='purple')
plt.plot(xi, dH, color = 'green', linestyle="--")
plt.axhline(y=0, color='black', linestyle='-', linewidth=1)
plt.fill(np.concatenate([xi, xi[::-1]]),
         np.concatenate([dH - 1.00 * sigma,
                        (dH + 1.00 * sigma)[::-1]]),
         alpha=.5, color = 'forestgreen', ec='None')
plt.fill(np.concatenate([xi, xi[::-1]]),
         np.concatenate([dH - 1.9600 * sigma,
                        (dH + 1.9600 * sigma)[::-1]]),
         alpha=.5, color = 'lightgreen', ec='None')

# legenda, label e título
plt.xlabel('$z$', fontsize=15)
plt.ylabel('$H(z) - H^{fid}(z)$', fontsize=15)
plt.legend(loc='best')
#plt.savefig('dH_recon_gapp.pdf', format='pdf', bbox_inches='tight')
plt.show()